# Generated by Django 5.0.14 on 2025-04-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('Jurusan', models.CharField(max_length=50)),
            ],
        ),
    ]
