# Generated by Django 5.0.14 on 2025-04-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama_jurusan', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='mahasiswa',
            old_name='Jurusan',
            new_name='jurusan',
        ),
    ]
